### ISSUE TITLE
please make output type optional

### ISSUE THREAD

**Issue by hopalongrock** [vaeth/calc-extension#1]
Hello,

Thank you, this add-on knows everything what I used in Scientific Calculator add-on

Because I mostly use decimal integers, please make possible to display the integer  result  optionally only in decimal notation,, The hex and octal numbers are unnecessary and disturb my reading of the result.

The input field length probably could be greater, to avoid the unnecessary scrolling, for example
-9239-6966-4706+500-11942-28859-2899-16203-2060-182955-2220-7774-14897-23360

**Comment by vaeth** [comment]
I also do not like the 3 alternatives output, but I did not find a better way to handle this.

Radio buttons have the problem with location: Placing them at the beginning is inconvenient when you have a huge page of calculations, and if placing them in every line (e.g. at the result) is even more confusing than simply printing the 3 results.

One could introduce a special syntax/variable to switch output style, but this is completely non-standard and not self-explaining. This is already a serious problem with "#".

In the new release (version 0.2), I restricted at least the alternative output to integer numbers >7.

**Comment by hopalongrock** [comment]
I would place the output style definition in the add-on Options, as other developers do.
I never use hex or oct numbers.

...

In the options I see an error:

![image](https://user-images.githubusercontent.com/6840865/36351869-f9f99e60-14af-11e8-8f34-a806df49978f.png)

**Comment by vaeth** [comment]
I will think about the idea with the options, although this is confusing for a "plain" application like this.
It would be better to have a quick way to select only one output format.

Concerning the length of the input field, there is the problem that once I specify one, it possibly restricts the supported displays/environments (e.g. too long might be very inconvenient for android): Without setting a value, the choice is left to the browser.
(For calculations like yours, it is perhaps better to press enter and continue with #+... in the next line).

Thanks for the report concerning the options; I couldn't find why it didn't start on android, but this is probably the reason.

**Comment by hopalongrock** [comment]
I think a big difference, that I don't have a smartphone and Android - I use a PC with Windows 10, with a wide screen, I feel I have to write into little "keyhole", the length of the input field may again be an option.
I wouldn't like to cut my original expression into pieces using #.
I can imagine even a multi-line calculation, where the add-on opens a new line when it is needed to continue the expression, and for Enter calculates the expression. (for example this paragraph could be the expression, displaying the result for Enter into the new line).

Of course I do not know what can you do in a browser's add-on.

**Comment by vaeth** [comment]
The current version in the master branch now contains 2 specials '...' and "..." which can be inserted anywhere in an expression.
With the '...' special, e.g. '60' the input size will change to 60.
With the "..." special, e.g. "16" the output format will change to hexadecimal.
Numbers are now output in only one format (by default in decimal).
The explanation in the title head describes these specials.
The options page is fixed.

If you are able to test (load the manifest.json with "about:debugging"), please do so and let me know your opinion.

Otherwise, I will probably release this new version 1.0.

**Comment by vaeth** [comment]
Thinking about your multiline suggestion:

I could use a so-called "textarea" element instead of an "input" element.
This would even have the advantage that you can simply resize it with the mouse if you want.

Unfortunately, pressing "enter" in a textarea just opens a newline; one has to use TAB to leave it which is again a problem on android. One can play tricks and check for keystrokes, but there might be browsers or platforms where this is not a good idea (actually, I already have no idea how it will be on android).

Without a proper way to "leave" the textarea, I am not sure how this might work; I do not want to insert a "calculate" button for every input field.

**Comment by vaeth** [comment]
In case you want to try: The branch "textarea" contains such a multiline experiment (currently without checking the return key).

**Comment by vaeth** [comment]
Playing around a bit with textarea, I came to the conclusion that even if checking the return key would be reliable, it is aginst user expectations with textarea elements.

Either I have to drop the textarea idea completely or place a "calculate" button" near each textarea.

What do you think is preferable?

**Comment by hopalongrock** [comment]
I'm sorry, but I don't find an xpi download link in master branch (v1.0) and textarea branch, please help, how can I download and install from Github.

I always used Enter key, it is almost automatic for me, don't think a calculate button is useful.

I like this conception with the many usable input fields, I can go back and correct the expression.

As I remember, I used calculator, where there is only one input field, the expressions and the results appear as displayed lines under each other, but I don't really liked this type of calculators.

**Comment by vaeth** [comment]
To get an xpi, I must let it sign by mozilla, first. There are persons involved who do this, so I cannot just produce an xpi for testing.

To test the extension you have to clone or download it (if you don't have git, use "clone or download" and download the zip file and unpack it). Then use in firefox the address "about:debugging" and there the button "load temporary extension". Then select the `manifest.json` file in the downloaded directory.

I have currently decided for the textarea solution with the additional button.
(The "textarea" branch mentioned above no longer exists; if necessary, the roll back has to happen by checking out an earlier version.)

Pros of this button:

1.  I already found people who were looking for such a button or entered "=" at the end of the formula, because this is what they know from calculators.
2. If you are a keyboard user, the presence of such a button is only slightly more inconvenient: Instead of "return" you have to press "tab + return".
3. Main pro: You have multiline input which you can resize how it is convenient for you.
4. You can even use newlines to make your formula readable (of course, spaces and newlines between tokens are ignored by the parser).
5. With the button, it is completely clear when the formula is evaluated. Without the button, if you were going back to a previous formula and pressed enter, there was no recalculation unless you modified the formula. (I cannot easily fix this: The browser does not send the event for updating in this case.) The problem here is if one relies on the meaning of # which is then perhaps not updated as one might expect.

Cons:

1. It hinders very quick successive entering of formulas.

**Comment by hopalongrock** [comment]
Excellent !

When we are at the bottom, I have to scroll to see the "=' button.

![image](https://user-images.githubusercontent.com/6840865/36365987-45c08560-154c-11e8-8027-bf8577a822c4.png)

How can I clear the screen when the old lines are disturbing?

Is it possible to save the calc tab data for a firefox session, or at least until Undo Close Tab?

A copy text (expressions and results) to clipboard and/or save to file feature would be very useful.

**Comment by vaeth** [comment]
To be honest, my pros and cons list was wrong: 2. is actually a "cons" (only not so bad) and of course there might be missing 3. some users might expect return to "just work".

For your convenience, I have produced an "inputelement" branch (to download it as zip, you have to select it before pressing "download or clone"; if you have cloned used git, use `git checkout inputelement` to switch to this branch). The main difference of that branch to the v0.2 is that the default input width is 60, and that you can use e.g. `'100'` to change all input field sizes (including previous ones).

Concerning your other questions:

> When we are at the bottom, I have to scroll to see the "=' button.

This is browser specific behaviour which probably cannot be changed. Pressing "tab" should work anyway.

> How can I clear the screen when the old lines are disturbing?

You can remove the tab and open a new (by pressing the symbol again). However, in a new tab all of your variables (including #) are cleared, too. I could implement it that variables (and #) are never forgotten until you close the browser, but I think it would contradict user expectations to not reset them when you open a new tab.
Currently, there is no way to "only" clean (without resetting anything): This would require a new button somewhere (or perhaps also one in every line to "remove" only that line).
On the other hand, you can just go to a previous input element/area and re-use that for a completely new formula.

> Is it possible to save the calc tab data for a firefox session, or at least until Undo Close Tab?

Both would require additional buttons which would need to be placed somewhere. But space is valuable for this extension, so I am hesitating. Also, there are many options for storing data:
Data might be stored/restored locally (i.e. for all firefoxes on your machine) or possibly alternatively stored/restored remotely (i.e. syncing between various machines with firefox sync set up correspondingly). Also, the stored data might contain the "visible" content or the variables or both (also, there is the question whether to include the '#' variable). (Neither of these two is trivial to implement in the current way the extension is implemented internally, but all could be done.)
In any case, there is the problems that variables and # might use precision, because they must be converted to decimal before saving. (The same problem occurs if variables should be shared across browser tabs)

> A copy text (expressions and results) to clipboard and/or save to file feature would be very useful.

This would again need an additional button. Moreover, I am not sure how this should look like if a text area contains multiple lines: How to distinguish in the selection between text area and output?

**Comment by vaeth** [comment]
I forgot: Storing data (no matter whether locally or syncing) and probably also using the clipboard requires that the extension is granted permissions. This might prevent users from installing the extension, because theoretically these permissions might be misused. I am not sure at all whether a webextension can save files (even if permissions are granted).

**Comment by hopalongrock** [comment]
It's great, Tab or Enter gives the result
Changing the all sizes with '100' is good, documents itself. Could you retain resizing the input field with mouse from the master?
I understand the data storing problem,  but the copy could be solved, for example starting the lines with  a "?" and "=" character, or something like this.
I see, you avoid buttons, maybe a 'copy' command (like '100') could be used.

**Comment by vaeth** [comment]
> Tab or Enter gives the result

Only if the input was changed. As mentioned, there is the problem with # which is not updated if you press enter if you did not change the formula.

> Changing the all sizes with '100' is good, documents itself.

Actually not. I am not sure how many people will understand the text in the beginning (or even just read it). In contrast, for the textarea variant the resizability documents itself visibly.

> Could you retain resizing the input field with mouse from the master?

No. This is exactly the problem: An input field is a different thing than a textarea with less features. That's the reason why entering '100' in the "input field" version changes all input field sizes while '100' in the "textarea" version only changes the defaults for new/future textares: For input fields there is no other "native" way to change their size.

All in all, I am still not sure what to use: textareas or input fields.
I am still somewhat in favor of textareas, because this is the only way if somebody wants to do a "huge" calculation. And the "=" button is certainly more intuitive for non-power users. On the other hand, for power users with "smaller" calculations, the input field is more convenient.

Perhaps this is something which should go into the options with textarea being the default?
But then again the '...' syntax would be confusing since it behaves differently in the input field case...

> starting the lines with a "?" and "=" character

The "=" character is bad since it might be used also inside a textarea (for variable assignment).
And the ? character is confusing. How about `=>` or `->`? Which is better?

> maybe a 'copy' command (like '100') could be used.

That again would need to be documented at the beginning and thus would take similar space as a button at the beginning. Maybe capturing Ctrl-a is possible for selecting all. I have to check. However, if it turns out that this (or modifying the paste buffer) needs special permissions, I will probably not implement it.

**Comment by hopalongrock** [comment]
I always copy the result of some previous expression, and didn't use a reference like # here or Ans in other program - of course I have to pay attention to copy the changed value.  This way I always see what happened.

For me the textarea solution in the  input element is more sympathetic - I do not know why anyone would just change the length of an input field.

**Comment by vaeth** [comment]
> For me the textarea solution in the input element is more sympathetic

Just to be sure that there is no misunderstanding:
The textarea solution is that with the `=` button where you can have multiple lines and use the moues to change the size of the field (but the return key does not start the calculation).

Please confirm whether this is indeed the one you prefer.

(The reason I ask: If even you as a power user prefer that solution, I think that I will just select it and not add an option to switch between the two choices. For non-power users the `=` button is probably clearer anyway.)

**Comment by hopalongrock** [comment]
Oops, what did I say! 

I prefer the "calc-extension-inputelement" branch, where a simple tab/enter is enough to calculate, and there is no "=" button, and the expression can be very, very long, even more than 150 characters, the input fields have the same length.

**Comment by vaeth** [comment]
OK, so it makes sense to have an option and to store the preferences at least locally.
This is now implemented.
I release this version immediately, because I will be rather busy now and do not know yet when I will find time again.

I will also close this bug now since it already involves too many topics. Feel free to open a new one.
