### ISSUE TITLE
version 4.0 - About Examples ... Editing appearance

### ISSUE THREAD

**Issue by hopalongrock** [vaeth/calc-extension#5]
version 4.0 - About Examples ... Editing appearance

It would be useful to be able to Collapse it to increase the free space for expressions, the 1st expression in this case could be immediately below "**calc-extension**",  or if necessary Expand it to get the current appearance - maybe the  "**1+2**" icon as a button could be used.

However, it would also be good if the items in Examples ... Editing would retain their state.
For example, if "Last Result and Clipboard", "Storage" and "Editing" were expanded, they would be the same when Calc is started again. See example:

![image](https://user-images.githubusercontent.com/6840865/36894009-5c932f88-1e0a-11e8-9fbb-01e3eb66dcff.png)

The Move Up and Down arrow in Editing is pale, barely visible, could be improved on it?

**Comment by vaeth** [comment]
All things should be fixed now in current master branch.

Concerning the arrows, this is a problem of your font (or font-rendering algorithm). Anyway, I changed to font-weight to "bolder" for these 2 buttons. I had also tried other symbols, e.g. U+x21A5 and U+x21A7, cf e.g. https://www.w3schools.com/charsets/ref_utf_arrows.asp but the results were worse.

**Comment by hopalongrock** [comment]
Thank you, works fine !

Here are the arrows now: ![image](https://user-images.githubusercontent.com/6840865/36914305-1b871408-1e4d-11e8-82f1-7fe8acc4f41b.png)
, but only the Up arrow is darker (bolder).

I use Firefox 58.0.2 on Windows 10, the default font in Firefox is Times New Roman, size 16.
Unfortunately I know nothing about any font-rendering algorithm.
I've been using these fonts for many years now, so far I have not needed anything else.
Because these are not standard symbols, I would prefer to see the Up and Down/Dn words/abbreviation (maybe along with the symbols).

I personally would remove the bold frame around the "x line .....expression" text, and would put the whole text on to the button. It is now too attractive for the eye.

The tooltip text over for "x window" is probably by chance German,.

Oops ! Now the cursor is in the proper line after a delete, great.

**Comment by vaeth** [comment]
> Only the Up arrow is darker

There was a typo. Should be fixed now.

> words/abbreviation

Not every language has such short words for this. Moreover, it would be rather inconsistent: + and X would then also have to be formulated (which is already longer even in English). And placing 6 longer texts (besides the explanation) in one line is too wide again for some screens

> I personally would remove the bold frame around the "x line .....expression" text

This is consistent with the layout of constants where also the explanation is put into an enclosing box.

> and would put the whole text on to the button

It does not really belong there; it is an additional information:

> It is now too attractive for the eye.

In a sense, this is the purpose: Otherwise the information is lost that you can get the same much quicker by keyboard. Nobody will read the instructions carefully enough to detect this. It is also not possible to rely on tooltips, since these are never displayed on android.

> The tooltip text over for "x window" is probably by chance German,

I translated it in the wrong file. (So in the German version the English version had remained) :)
This should also be fixed now.

**Comment by hopalongrock** [comment]
It's OK now.

But I must say that as a simple user, I'm not interested in the text "Evaluate an empty expression".
For me "x line" is as natural and understandable as "Clean line" or "Clean window" and they are just equally dangerous. For example, **Undo (Ctrl Z) does not work** after "Clean line" and "Clean window".

**Comment by vaeth** [comment]
The current version in master branch is now ready for testing for the next release.
There were quite a lot internal changes necessary since my last posting here; I hope they didn't introduce any new bugs.

Most remarkable changes:
- Storing of accordeon state has become an option
- Buttons to expand/collapse accordeon
- Calculation button is always there
- Default to non-textarea, but still provide textarea as an option.
- Issues solved with restoring session when the textarea/input was changed during session.
- Improved layout (e.g. avoided most of the ugly boundary boxes).
- Most cumbersome change: Everything is endowed with a tooltip now

However, recall that too important information must not be hidden in tooltips, since android users cannot see them.

> I'm not interested in the text "Evaluate an empty expression".

I found now a compromise which is much shorter.

**Comment by hopalongrock** [comment]
The accordeon (accordion in English as I see) looks really good now - is the accordion term used generally for this type of construction?

The state is saved always, regardless of the "Store accordeon state" setting.

I would name the buttons as "Full Expand" and 'Full Collapse", although the tooltips contains "... all details". 

I would place "Store accordion state" in the Options item, for example after the "width:height" setting and buttons. In the addon options they appear together too.

I don't like, that the click works everywhere on the item's line, not only on the black triangle at the beginning of the line.

If "width:height" 0:0 and  80:5 identical, why there are two buttons - or are  they not identical ?

If the "Input expression in textarea" option is off:
 - Why is the "width:height" settable, why are the buttons clickable?
 - for Enter the result appears, but the cursor remains in the current line, doesn't move to the newly  created expression line

**Comment by vaeth** [comment]
> accordion in English 

Thanks a lot. I would never have realized that.

> is the accordion term used generally for this type of construction?

I read it in some texts discussing its implementation in html5. I am not happy with the formulation (although it is somewhat intuitive), but I didn't find a better formulation to make clear that only the "open state" of the entries is saved and not the whole content (with e.g. options).

> The state is saved always, regardless of the "Store accordeon state" setting.

I think there is a misunderstanding. What happens (if there is no bug) is that the state is saved whenever you open/close a detail until you uncheck the button. Then the last saved state remains. This is the only possible way, since you might have several tabs open, and when you store in one and uncheck the option in the other you would get unexpected results. (A tab which stores always pushes changes to the other tabs.)

As a "workaround", I could introduce a button to clear the saved accordion state.
(And when I am at it, I could also introduce a button to clear the stored options).

On the other hand, there is the "clear storage" button which clears all, making the above buttons (and actually also the "clear stored session" button) partially superfluous.

What is your opinion: Keep it as it is, remove the "clear stored session" button, or add the new buttons.
In the latter case: Add them to the "Storage" section or also to the options (preferences) page?

> I would name the buttons as "Full Expand" and 'Full Collapse"

There is again the space issue, because

> I would place "Store accordion state" in the Options item

this is not possible: If you open the options item and then uncheck the option, you will remain with an open options item being saved. You would have to use the workaround to press the "clear accordion state" button (if I should introduce it), and this button is perhaps even in a different section "storage".
(Of course, I could introduce the same button twice, but this is even more confusing).

> I don't like, that the click works everywhere on the item's line

I don't like neither, but the "details" element is a browser built-in which cannot be modified. (Unless everything is programmed manually or by including a third-party library which I both do not intend to do.)
In fact, I even had to play tricks (add an event handler to cancel default actions) to avoid toggling when you click the buttons or the checkbox, or even the checkbox text in the first line. I could use a similar trick also for the other texts, but then there is still some space which is not covered:
You can see this if you carefully click on the empty space between the checkbox and the text "store accordion state" which will toggle the main entry, because my event handler is not called.

On the other hand, since it is the browser's default, maybe I should leave it as it is since users might expect it to work that way.

> If "width:height" 0:0 and 80:5 identical, why there are two buttons

The buttons insert the text into the input field. Of course, the inserted text is different. Also the text which will appear in the option is different when you evaluate the expression.

> Why is the "width:height" settable, why are the buttons clickable

In this case, the height is ignored, but the "width" is the width of all input lines (even of already existing ones) which will change.

> for Enter the result appears, but the cursor remains in the current line,

This was one of several bugs which I found meanwhile (due to the restructuring of internals).
The current version had again some restructuring and now hopefully works correctly.

**Comment by hopalongrock** [comment]
I understand - I don't think I would use calc with different styles simultaneously, so I would never set  "Store accordion state". The working without this setting is enough for me.

The calculation work better now ("Input expression in textarea" is disabled), however the ~> before the result is input, and tab and shift tab stops there - this is not necessary, and it did not work this way previously.
![image](https://user-images.githubusercontent.com/6840865/36946364-184e6064-1fbc-11e8-9e66-a2cddce48020.png)

**Comment by vaeth** [comment]
Finally, a new release candidate:

Your misunderstanding concerning the saving of the accordion state, gave me the right idea:
Now whenever that option is switched off, the stored state is tacitly erased. By tacit, I mean without resetting to the default in any open window. (This was tricky to implement, because the handler for changed storage cannot see the reason for deletion.)
Your misunderstanding seems to indicate that this is even what users expect.

With this change of behaviour, it is now reasonable to put the option to the "Options" section. Now also the chance has decreased that this option saves more than the "open" states of the accordion.

Concerning making the texts non-clickable, I think that I will not do it:
1. First of all, it is the browser's default, so user might be used to it.
2. There is no real disadvantage: What other reasons might users have to click the summaries if not for toggling the details? It might even be convenient, because the small triangle is hard to hit.
3. I could not hide the huge visible box anyway but only make the clicking in that box has no effect unless the triangle is hit.

>  it did not work this way previously.

By "previously", I assume that you mean when there was no button. ;)
I know that this button is superfluous, but it was a requirement to make the non-textarea input the default. As mentioned, my first "tester" wondered what he should do after he entered the formula...

Fortunately, html5 does support excluding items from the tab cycle list, so I exclude now buttons of non-textareas; for textareas the situation is different, because there is no alternative "enter" key to replace the button.

**Comment by vaeth** [comment]
BTW: The '80:5' button is now the perhaps better example '60:3', so people do not get confused...

**Comment by hopalongrock** [comment]
Although non-clickable texts would be really better, it's not problem for me - I have to be careful not to accidentally click on a free but sensitive (clickable) area - this sometimes happens when my finger is on the mouse. 

Now the accordion is not saved automatically, instead "tacitly erased" but if I set the desired accordion state, and save it, then the next session will come "automatically" in the saved state, and "Store accordion state" will be off. This is nearly the same, as it was originally.

I can't go to the "width:height" and the "output base" field with the mouse, the cursor jumps to the expression input field. Tab and Shift-Tab works well.

Are the two "Redraw .." button for mobiles? I think for PC monitors they are superfluous.

**Comment by vaeth** [comment]
> and "Store accordion state" will be of

Store accordion state is an option. So you either have to set it in the preferences page or press "store options" to make the change "permanent".

But I got also angry by this and reworked again the internals quite a bit:
Now the "store options" is a checkbox. So if you set it, all your option changes (like setting the "store accordion state" option) will be automatically stored as well.

Again, this reworking of internals might have led to further bugs...

> I can't go to the "width:height" and the "output base" field with the mouse,

This was too strong an attempt to never let the input field loose focus. This is fixed now by making explicit exceptions for these fields.

> Are the two "Redraw .." button for mobiles

No. As the title (=tooltip) text explains, they are there to let an option change input<->textarea (or a size change for textarea) have effect on the corresponding line or the whole window, respectively. That's why the buttons are after this option.

**Comment by hopalongrock** [comment]
I set 60:2, but there is 3 line:

![image](https://user-images.githubusercontent.com/6840865/36960361-03801728-2047-11e8-936e-c8332e148696.png)

Now I understand the redraw, it's a big help.

> Now the "store options" is a checkbox. So if you set it, all your option changes (like setting the "store accordion state" option) will be automatically stored as well.

In add-on options "store options" is enabled. If in the session I disable this option -i.e. make a change, this option change isn't saved, if I start a new session, it will be enabled again. If I don't want this, I have to disable it in add-on options.

**Comment by vaeth** [comment]
> this option change isn't saved

This is the corner case: Still store/propagate this change or not?
I had made the wrong decision, because without storing it, it had been impossible to unset this option without the preferences page.
Fixed in the current master branch.

I think it is time to release v5.0.

**Comment by vaeth** [comment]
BTW, I had tried to use the trick to make the summaries non-clickable, but then also the triangle did not work. So, currently, I do not know how to solve this problem (with reasonable effort).

**Comment by hopalongrock** [comment]
I'm sorry, but now if I set "Store options" in the session and change for example width:height, this is not saved - if exit and start a new session, I get old width:height.
I don't know now, when the option should be saved ? Does it happen immediately after an option changed? Maybe a simple Save Options button would be better.

The size is 60:2, but there is still 3 lines instead of 2.

Can it help if the triangles are placed in some other blocks, forms, ..., to live a separate life from the rest of the lines?
Or would it be problem, if the triangles would be in expanded and collapsed state the same simple buttons, containing black full circle. The rest of lines could be simple text or button, as it needed.

**Comment by hopalongrock** [comment]
OK, if the size is 60:1, there are 2 lines, instead the default 5 there are 6 lines,  ie there are always 1 row more

**Comment by vaeth** [comment]
I had simply forgotten to store the size and base changes. This is fixed now.
Also storing of changes induced by ! ? expressions had been missed.

The mechanism is meant to work like this: While the "store options" is switched on, every option change is immediately saved/pushed (you can see this if you open a second tab).
When you switch on the "store options" (when it was switch off previously), all options are saved/pushed (no matter whether you changed them or not). This is probably what the user expects.
(Otherwise it would mean: If the user switches the "store options" from of to on his previous changes to the options would not be saved until he does the changes again.)

> Maybe a simple Save Options button would be better.

This is what was there before, but which was no good, either.
Anyway, switching the "store options" checkbox has the same effect (which as explained above is probably what the user expects).

> Can it help if the triangles are placed in some other blocks, forms

The triangles are drawn by the browser. I can at most put the text in some other block.
Anyway, I played now with CSS styles and were able at least to "shorten" the lines somewhat.
Perhaps this is now a good compromise.

> The size is 60:2, but there is still 3 lines instead of 2

In my firefox, there are 2.5 lines. It is probably font-dependent.

**Comment by hopalongrock** [comment]
Eventually an unwanted change due to a click in the accordion can be undone easily with a new click.

Here is something funny:

 ![image](https://user-images.githubusercontent.com/6840865/36989718-d244ffd2-20a2-11e8-8b76-f218d3268dcf.png)

Could you place "Store accordion state", "Store options" and "Clear storage" in one line next to each other?

Apart from these, as for me, it looks to work fine now.

**Comment by vaeth** [comment]
> Eventually an unwanted change due to a click in the accordion can be undone easily with a new click.

Wasn't this always so for you?

> Here is something funny

I also found (and fixed) that already. That's why I hate javascript: It tries to be clever and make sense of a wrong type instead of crashing/reporting an error. Otherwise I would have found it immediately.

> Could you place "Store accordion state", "Store options" and "Clear storage" in one line

I am not sure whether this is a good idea: These things are very different.

**Comment by hopalongrock** [comment]
> Wasn't this always so for you?

Yes, it was - but I thought it's not too hard to solve this issue.

> I am not sure whether this is a good idea: These things are very different.

I think they are not so different, to cause confusion next to each other, and occupy less space.

**Comment by vaeth** [comment]
OK. Thanks for all the testing and hints.

I put the 3 options now on one line and made a few other cosmetic changes.
Releasing now

**Comment by hopalongrock** [comment]
It was my pleasure.
